# Generated by Django 5.2.7 on 2025-11-19 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_autor_libro_resena_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
